[project]
name = "data-processor"
version = "1.0.0"
requires-python = ">=3.13"
description = "FastAPI service for medical data transformation"
dependencies = [
    "utils",
]

[tool.uv.sources]
utils = { workspace = true }