name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  per-service:
    name: CI for ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [
          data_processor,
          model_service,
        ]


    steps:
      - uses: actions/checkout@v4

      - name: Detect changes for ${{ matrix.service }}
        id: changes
        run: |
          git fetch origin main
          if git diff --quiet origin/main...HEAD -- "services/${{ matrix.service }}/"; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Skip if no changes
        if: ${{ steps.changes.outputs.changed == 'false' }}
        run: |
          echo "✅ No changes in services/${{ matrix.service }}, skipping tests."
          exit 0

      - name: Install uv
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache uv dependencies
        if: ${{ steps.changes.outputs.changed == 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: uv-${{ runner.os }}-

      - name: Sync environment
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: |
          cd services/${{ matrix.service }}
          uv sync

      - name: Lint with Ruff
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: |
          cd services/${{ matrix.service }}
          uv run ruff check .

      - name: Check formatting
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: |
          cd services/${{ matrix.service }}
          uv run ruff format --check .

      - name: Run tests
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: |
          cd services/${{ matrix.service }}
          uv run pytest -v

      - name: Build package
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: |
          cd services/${{ matrix.service }}
          uv build